future: true
permalink: /blog/:year/:title.html
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "smart"]

assets:
  cache_type: memory
  digest: true

lsi: false
highlighter: rouge

plugins:
  - jekyll/itafroma/indent_filter
  - jekyll-redirect-from
  - jekyll-assets
